### ISSUE TITLE
Requirement on METIS int size

### ISSUE THREAD

**Issue by ivan-pi** [sfilippone/psblas3#13]
Hello @sfilippone,

I would like to use PSBLAS for an unstructured lattice Boltzmann code (I've seen it used this way in some of your slides).

Running the configure script with `./configure --with-metis=-lmetis` I can see the following:
```
checking metis.h usability... yes
checking metis.h presence... yes
checking for metis.h... yes
checking for METIS integer size... 32
checking for METIS real size... 32
checking for METIS_PartGraphKway in -lmetis ... yes
checking for METIS_SetDefaultOptions in -lmetis  -lm  ... yes
```

however, the final configuration says:

```
	METIS usable          : no
	METIS bitsize         : 32
	METIS realsize        : 32
```

I installed METIS using the `apt` command on Linux. From [previous experimentation](https://github.com/ivan-pi/fmetis) with METIS I know it can be compiled also with 64-bit integers in reals. 

Would this solve my issue?

Ivan

**Comment by sfilippone** [comment]
Yes, it would solve your problem. The reason why the script says that METIS
is not usable is that METIS is used on matrices holding GLOBAL indice, i.e.
in PSBLAS jargon they are PSB_LxSPMAT_TYPE   and the default configure sets
Lx to use 8-byte integers; so, using the 64-bits version of METIS should
solve the problem.

If it doesn't work, let me know

Cheers
S.

**Comment by sfilippone** [comment]
(a cheap alternative would be to configure   --with-lpk=4   to use 4-bytes
integers on global indices; but then, of course you cannot have a global
index space with more than 2G indices)

**Comment by sfilippone** [comment]
The new release 3.7.0 has improved support for both 32 and 64 bit versions of METIS.
