### ISSUE TITLE
question on matrix/rhs assembly

### ISSUE THREAD

**Issue by AliE89** [sfilippone/psblas3#19]
Sorry guys, I am an absolute beginner with this lib really. 

Can you point me to an example to assemble a matrix and a rhs in parallel? 

I already have all the info about local to global mapping of indices for the coefficients, so I would need to know better what are the operation needed to put them iniside your container.

 if you are a bit used to petsc, I need the equivalent of matSetValues and matAssemblyBegin()/matAssemblyEnd() .

Thanks for the help

**Comment by sfilippone** [comment]
You can look at
psblas3/test/pargen
psblas3/cbind/test/pargen

Salvatore

**Comment by sfilippone** [comment]
Can we close this issue, or is there still something to be looked at?

**Comment by AliE89** [comment]
Ciao Salvatore,

I am still looking at this really. Did not find enough time to look at it
carefully, i am afraid. It's something I do during my free time so my
inertia is quite hig.

Il Mer 25 Mag 2022, 09:43 Salvatore Filippone ***@***.***> ha
scritto:

**Comment by sfilippone** [comment]
Is it possible to close this now? 
Thanks

**Comment by AliE89** [comment]
Sure!

Il Ven 5 Ago 2022, 13:35 Salvatore Filippone ***@***.***> ha
scritto:
