### ISSUE TITLE
METIS version constraint

### ISSUE THREAD

**Issue by ivan-pi** [sfilippone/psblas3#20]
Are there any constraints on which versions of METIS are supported, i.e. 4.0.3 or 5.1.0?

**Comment by sfilippone** [comment]
If by metis 4.0.3 you mean the version of (serial) metis contained in ParMETIS 4.0.3, then yes, it works. 
There should be no other constraints, given that the METIS code has had a very stable interface for quite some time  by now.

**Comment by ivan-pi** [comment]
That's odd, since the configure script indicates a missing function:
```txt
checking for metis.h... yes
checking for METIS integer size... unknown
checking for METIS real size... unknown
checking for METIS_PartGraphKway in -lmetis ... yes
checking for METIS_SetDefaultOptions in -lmetis  -lm  ... no. Unusable METIS version, sorry.
checking Compatibility between metis and LPK... no
```
(also not sure how `-lm` creeped into that check...)

For more background, I am trying to use [Spack](https://spack.readthedocs.io/en/latest/index.html) to build and install PSBLAS.

The specification (dependency graph) is
```
psblas@3.8.0%gcc@11.2.0~amd+metis~serial arch=linux-sles15-haswell
    ^intel-mkl@2020.4.304%gcc@11.2.0~ilp64+shared threads=none arch=linux-sles15-haswell
        ^cpio@2.12.3%gcc@11.2.0 patches=d22633c368b8aedf4c08b23b6fbaa81a52404c8943ab04926404083ac10f1a4b arch=linux-sles15-haswell
    ^intel-mpi@2019.12.320%gcc@11.2.0 arch=linux-sles15-haswell
        ^patchelf@0.13%gcc@11.2.0 arch=linux-sles15-haswell
    ^metis@4.0.3%gcc@11.2.0~gdb~int64~real64+shared build_type=Release arch=linux-sles15-haswell
```

The `METIS_SetDefaultOptions` appears to be available in both [parmetis-4.0.3.tar.gz](http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz) and [metis-5.1.0.tar.gz](http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz), so it may be something else is wrong. 

Is the plan to keep the current build tools or switch to CMake eventually (#12)?

**Comment by sfilippone** [comment]
Can you send me config.log please?
I'll take a look asap

**Comment by sfilippone** [comment]
checking for METIS integer size... unknown
checking for METIS real size... unknown

I have a feeling the problem is in these two lines 

S.

**Comment by ivan-pi** [comment]
You are indeed correct. The Spack provided Metis library used 32-bit integers by default. I've adjusted and I now get:

```txt
checking metis.h usability... yes
checking metis.h presence... yes
checking for metis.h... yes
checking for METIS integer size... 64
checking for METIS real size... 32
checking for METIS_PartGraphKway in -lmetis ... yes
checking for METIS_SetDefaultOptions in -lmetis  -lm  ... yes
```
