### ISSUE TITLE
Rename base/modules/aux for windows compatibility

### ISSUE THREAD

**Issue by zbeekman** [sfilippone/psblas3#4]
Hi Salvatore et al,

I tried to clone psblas3 on a windows machine and the clone succeeds but the checkout fails because `aux` is a reserved keyword on windows. For any windows support (and for the record I wouldn't be bothering with windows if I didn't have to) base/modules/aux needs to be renamed. I can submit a PR with the required changes.

**Comment by sfilippone** [comment]
Are you saying that under Windows I can NOT have a directory named as I
wish?
Wow,
Would "auxil" work?
S.

**Comment by zbeekman** [comment]
Yes, sadly, that IS what I am saying. I can submit a PR refactoring the source tree to use auxil instead of aux. Stupid windows....

Don't worry, we're not the first to run into this problem: https://github.com/swcarpentry/DEPRECATED-bc/issues/463

**Comment by sfilippone** [comment]
This is fixed in branch MixedI8, which is planned for merge into development relatively soon. 
Can we close this?

**Comment by zbeekman** [comment]
Sure, thanks!

**Comment by sfilippone** [comment]
Ok, fixed in branch, merge into development planned before SC18.
