### ISSUE TITLE
Bug in subroutine s_base_set_vect ?

### ISSUE THREAD

**Issue by jaslopes** [sfilippone/psblas3#9]
Hello,

I think there is a bug in the mentioned subroutine that results in a wrong behaviour operation. If you use

call v%set( vect, first, last )

the code does not allow "last" to be larger than "size( vect )". In my opinion, "last" should not be larger than "first + size( vect ) - 1"

Patch:

@@ -745,8 +745,9 @@ contains
     integer(psb_ipk_) :: info, first_, last_, nr

     first_=1
-    last_=min(psb_size(x%v),size(val))
     if (present(first)) first_ = max(1,first)
+
+    last_=min(psb_size(x%v),first_+size(val)-1)
     if (present(last))  last_  = min(last,last_)

     if (allocated(x%v)) then

**Comment by jaslopes** [comment]
But if you still consider size(vect)=10, first=21, last=30, I think this would generate an assignment
x%v(21:30) = vect(1:30-21+1)
which is valid.

However, currently it generates an assignment
x%v(21:10) = vect(1:10-21+1)
which does nothing, because of the line
last_=min(psb_size(x%v),size(val))

That's why I think that you should use
last_=min(psb_size(x%v),first_+size(val)-1)

My problem was that I was copying blocks from a vector of size 'n' and as soon as 'first' becomes larger than 'n' (but last <= first + n - 1), nothing is copied.

**Comment by sfilippone** [comment]
Hmm. Looks like you're right and I was wrong (possibly due to
insufficient amount of coffee this morning ;-) )

**Comment by sfilippone** [comment]
Fixed on development at [https://github.com/sfilippone/psblas3/commit/1a5ee8c46a4a332fce997522560d7b9f6dbde547](url)

**Comment by jaslopes** [comment]
Thanks!
